name: Bug Report
description: File a bug report
labels: ['bug']
body:
  - type: input
    id: version
    attributes:
      label: "App version"
      placeholder: "v1.2"
      description: Please specify the version in which the bug occurred. Dont know how to find the version? See [How to Find your App version](./readme/how_to_find.md#how-to-find-your-app-version).
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current behaviour
      description: What did Eura Tasks do? Please do not paste screenshots or videos into the field. Instead, upload them to the designated field.
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect Eura Tasks to do?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots and videos
      description: If possible, please include screenshots or videos

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output if applicable
      description: Please copy and paste any relevant log output in this field.
